services:
  n8n:
    build: .
    ports:
      - 5678:5678
    restart: always
    environment:
      - N8N_LOG_LEVEL=debug
      - N8N_METRICS=true
    volumes:
      - /mnt/d/radio_news_ai_agent/files:/files
      - n8n_data:/home/node/.n8n
volumes:
  n8n_data:      